### ISSUE TITLE
Docker compose exmaple?

### ISSUE THREAD

**Issue by SawkeeReemo** [monero-project/monero-gui#4307]
I use docker compose for several containers, but I'm not always sure how to convert a docker run command to a compose. Building on an Ubuntu LTS 22.04 system, Docker v26.0.2, Docker Compose version v2.26.1.

Here is my initial attempt, but would love some confirmation to know if I'm doing it correctly:
```
  monero:
    image: monero:build-env-linux:v0.18.3.3
    container_name: monero
    command: sh -c 'make release-static -j4'
    volumes:
      - /my_config_dir/monero:/monero-gui
```

My guesses:
**image tag**, assuming that's correct?
**command**, no idea if I need that or what to do there.

Any help would be greatly appreciated! And then once it's running, how do I access it? I don't see any ports or environmental variables to add, which usually determines how I access a container.
